name: Release Types

on:
  workflow_call:
    inputs:
      target_branch:
        required: true
        type: string
      release_types:
        required: true
        type: string

permissions:
  actions: write
  contents: write

jobs:
  initialize:
    name: Initialize
    runs-on: ubuntu-20.04
    outputs:
      release_types: ${{ env.release_types }}
      target_branch: ${{ env.target_branch }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.target_branch || github.ref_name }}
        token: ${{ secrets.KIALI_PROJECT_TOKEN || github.token }}
    - name: Configure git
      run: |
        git config user.email 'kialiProject@gmail.com'
        git config user.name 'kialiProject'
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: "14"
        cache: yarn
        cache-dependency-path: yarn.lock
    - name: Install dependencies and build ðŸ”§
      working-directory: ./packages/types
      run: yarn install && yarn build    
    - name: Major release
      if: "${{ github.event.inputs.release_types == 'major' }}"
      working-directory: ./packages/types
      run: yarn version --major --no-git-tag-version
    - name: Minor release
      if: "${{ github.event.inputs.release_types == 'minor' }}"
      working-directory: ./packages/types
      run: yarn version --minor --no-git-tag-version
    - name: Patch release
      if: "${{ github.event.inputs.release_types == 'patch' }}"
      working-directory: ./packages/types
      run: yarn version --patch --no-git-tag-version
    - name: Get version 
      working-directory: ./packages/types
      run : |
        echo "NEW_VERSION=$(cat package.json | jq -r '.version')" >> $GITHUB_ENV          
    - name: Publish package ðŸ“¦
      working-directory: ./packages/types
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
        npm publish --no-verify-access
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Push changes to repository
      working-directory: ./packages/types
      run: |
        git add "package.json"  
        git commit -m "chore: release Types package to version ${{ env.NEW_VERSION }}"
        git tag ${{ env.NEW_VERSION }}  
        git push origin && git push --tags